apiVersion: agones.dev/v1
kind: Fleet
metadata:
  name: simple-game-server
spec:
  replicas: 1
  template:
    spec:
      ports:
        - name: default
          containerPort: 9000
      template:
        spec:
          containers:
            - name: simple-game-server
              image: scalalang22/agones-sample-server
              command: ["dotnet", "SimpleGameServer.dll"]
              resources:
                requests:
                  memory: 64Mi
                  cpu: 20m
                limits:
                  memory: 64Mi
                  cpu: 20m