apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gameserverallocation-role
  namespace: default
rules:
- apiGroups: ["allocation.agones.dev"]
  resources: ["gameserverallocations"]
  verbs: ["create"]
