apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    app: lobby-server
spec:
  type: {{ .Values.lobby_server.service.type | default "ClusterIP" }}
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: lobby-server
