apiVersion: v2
name: apps
description: Sample game server application & lobby server for Agones
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - games
  - multiplayer
  - dedicated server